BEGIN;
UPDATE cafes SET level = 'C' WHERE id = 'mel-disc-1110';
UPDATE cafes SET level = 'C' WHERE id = 'mel-disc-1004';
UPDATE cafes SET level = 'C' WHERE id = 'mel-disc-1050';
UPDATE cafes SET level = 'A' WHERE id = 'mel-disc-566';
UPDATE cafes SET level = 'C' WHERE id = 'mel-disc-1000';
UPDATE cafes SET level = 'C' WHERE id = 'mel-disc-1103';
UPDATE cafes SET level = 'C' WHERE id = 'mel-disc-507';
UPDATE cafes SET level = 'C' WHERE id = 'mel-disc-445';
UPDATE cafes SET level = 'C' WHERE id = 'mel-disc-621';
UPDATE cafes SET level = 'C' WHERE id = 'mel-disc-751';
UPDATE cafes SET level = 'C' WHERE id = 'mel-disc-741';
UPDATE cafes SET level = 'C' WHERE id = 'mel-disc-743';
UPDATE cafes SET level = 'A' WHERE id = 'syd-disc-232';
UPDATE cafes SET level = 'C' WHERE id = 'mel-disc-994';
UPDATE cafes SET level = 'C' WHERE id = 'mel-disc-706';
UPDATE cafes SET level = 'C' WHERE id = 'mel-disc-990';
UPDATE cafes SET level = 'C' WHERE id = 'syd-disc-345';
UPDATE cafes SET level = 'C' WHERE id = 'syd-disc-138';
UPDATE cafes SET level = 'C' WHERE id = 'syd-disc-780';
UPDATE cafes SET level = 'C' WHERE id = 'syd-disc-330';
UPDATE cafes SET level = 'C' WHERE id = 'syd-disc-911';
UPDATE cafes SET level = 'C' WHERE id = 'syd-disc-863';
UPDATE cafes SET level = 'C' WHERE id = 'syd-disc-297';
COMMIT;
