BEGIN;
UPDATE cafes SET website = 'asakusaya.com.au/' WHERE id = 'mel-disc-600';
UPDATE cafes SET website = 'shallwecoffee.lovable.app/' WHERE id = 'mel-disc-727';
UPDATE cafes SET website = 'foremost-docklands.square.site/' WHERE id = 'mel-disc-731';
UPDATE cafes SET website = 'www.cafetaza.com.au/' WHERE id = 'syd-disc-013';
UPDATE cafes SET website = 'trico.au/' WHERE id = 'syd-disc-109';
UPDATE cafes SET website = 'www.bacinobar.com/surry-hills/' WHERE id = 'syd-disc-117';
UPDATE cafes SET website = 'cafecandm.com.au/' WHERE id = 'syd-disc-192';
UPDATE cafes SET website = 'cafecasa.rf.gd/' WHERE id = 'syd-disc-291';
UPDATE cafes SET website = 'chefspalette.au/' WHERE id = 'syd-disc-389';
UPDATE cafes SET website = 'www.coffeedripcafe.com.au/' WHERE id = 'syd-disc-783';
UPDATE cafes SET website = 'ohmatcha.com.au/' WHERE id = 'syd-disc-851';
UPDATE cafes SET website = 'tamagawa-japanese.lovable.app/' WHERE id = 'syd-disc-864';
UPDATE cafes SET website = 'www.snowbloom.com.au/' WHERE id = 'syd-disc-899';
UPDATE cafes SET website = 'misolado-sydney.com/' WHERE id = 'syd-disc-910';
UPDATE cafes SET level = 'C' WHERE id = 'mel-disc-727';
UPDATE cafes SET level = 'A' WHERE id = 'mel-disc-731';
UPDATE cafes SET level = 'C' WHERE id = 'syd-disc-013';
UPDATE cafes SET level = 'A' WHERE id = 'syd-disc-109';
UPDATE cafes SET level = 'C' WHERE id = 'syd-disc-192';
UPDATE cafes SET level = 'C' WHERE id = 'syd-disc-291';
UPDATE cafes SET level = 'B' WHERE id = 'syd-disc-851';
UPDATE cafes SET level = 'C' WHERE id = 'syd-disc-116' AND level = 'D';
COMMIT;
